# Generated by Django 4.2.7 on 2023-11-09 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_remove_userprofile_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='verification_code',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='confirmation_code',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
