# Generated by Django 4.2.7 on 2023-11-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_verification_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='confirmation_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
