# Generated by Django 4.2.7 on 2023-11-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_delete_user_alter_post_category_alter_reply_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Танки', 'Tanks'), ('Healers', 'Хилы'), ('DD', 'ДД'), ('Traders', 'Торговцы'), ('GM', 'Гилдмастеры'), ('QG', 'Квестгиверы'), ('Кузнецы', 'Кузнецы'), ('Leatherworkers', 'Кожевники'), ('Potions', 'Зельевары'), ('Spell', 'Мастера заклинаний')], max_length=15, verbose_name='Категория'),
        ),
    ]
